###read all products
GET http://localhost:3200/test

###read a user by brand
GET http://localhost:3200/test/jsersey

### create new product
POST http://localhost:3200/test
content-type:application/json

{
  "productid":111,
  "name":"jersey butter milk",
  "brand":"jersey",
  "price":40

}

###to update 
PUT http://localhost:3200/test
content-type:application/json

{
    
  "productid":111,
  "name":"jersey milk",
  "brand":"jersey",
  "price":40

}

###delete a user by 111
DELETE http://localhost:3200/test/111
